---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: proxmox
version: 0.0.1
readme: README.md
authors:
  - YOUR NAME (github.com/YOURGITHUB)
description: Community modules and plugins for Proxmox.
license_file: COPYING
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - community
  - proxmox
repository: https://github.com/ansible-collections/community.proxmox
# documentation: ...
homepage: https://github.com/ansible-collections/community.proxmox
issues: https://github.com/ansible-collections/community.proxmox/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
